Obstacle avoidance for the back of the car
DIT112-V21/group-04 pull request #46
Opened 2021-05-10 20:02 UTC by Marble879

### Changes

1. Add obstacle avoidance to the back of the car.
2. Reduce the max speed of the car from 100% to 60% so that it is better suited for maneuvering in a hospital.
3. Fix an issue where the Arduino IDE couldn't compile the Arduino sketch.

### Issues
Resolves #34

2021-05-10 20:27 UTC, NilsDunlop approved these changes
After have tested the back speed values in the SMCE they seem to make the IRSensors identify obstacles properly as compared to before. Other than that, the code looks readable and good. Well done!

2021-05-11 10:19 UTC, MarkusJ299 requested changes
Looks good overall. I just added a minor suggestion. Let me know what you think.

2021-05-11 10:19 UTC, MarkusJ299 commented on arduino/smartcar/smartcar.ino
> +  }
Would it be better to use another boolean variable that is returned in this method? As a result, only one return statement would be needed and the else-condition would no longer be necessary.

```suggestion
  boolean isObstacleDetected = false;
  
  if (isFrontDetected || isBackDetected){
    car.setSpeed(stoppingSpeed);
    isObstacleDetected = true;
  }
  
  return isObstacleDetected;
```

2021-05-11 10:33 UTC, Marble879 commented on arduino/smartcar/smartcar.ino
> +  }
That's a great point! It improves the readability of the code - I'll add the changes now :+1:

2021-05-11 10:48 UTC, MarkusJ299 approved these changes
Looks good!

2021-05-11 12:05 UTC, puerto-hub approved these changes
Seems good! Great work by making two obstacle detection booleans.

2021-05-11 12:39 UTC, JihanP approved these changes
It looks good, nice that you restricted the speed for the car! Good job, keep going!

2021-05-11 13:54 UTC, Kevinayad approved these changes
Good job!

2021-05-11 13:54 UTC, gusasino reviewed
great work!

2021-05-11 13:55 UTC, merged